import React, { useEffect, useState } from 'react';
import { Box, Text, useInput } from 'ink';
import { CodingAgent } from '../../agents/src/codingAgent';
import { FsTool } from '../../tools/src/fsTool';
import { terminalTheme } from '../../ui/src/theme';

interface FileChange {
  path: string;
  action: 'add' | 'edit' | 'delete';
  content?: string;
}

interface MultiFileEditorProps {
  /** Prompt to send to CodingAgent for generating diffs */
  prompt?: string;
  /** Called when all changes are applied */
  onComplete?: () => void;
}

/**
 * Multi-File Editor component for the TUI.
 * Shows a preview of file changes generated by CodingAgent and lets the user
 * apply or discard them interactively.
 */
export const MultiFileEditor: React.FC<MultiFileEditorProps> = ({ prompt, onComplete }) => {
  const [changes, setChanges] = useState<FileChange[]>([]);
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [status, setStatus] = useState<'loading' | 'preview' | 'applying' | 'done' | 'error'>('loading');
  const [message, setMessage] = useState('Generating diff...');
  const [applied, setApplied] = useState<Set<number>>(new Set());

  // Load diff from CodingAgent on mount or when prompt changes
  useEffect(() => {
    const loadDiff = async () => {
      try {
        setStatus('loading');
        setMessage('Generating diff...');
        const agent = new CodingAgent();
        const result = await agent.generateDiff(prompt || '');
        const diffChanges = result?.changes || [];
        setChanges(diffChanges);
        setStatus(diffChanges.length > 0 ? 'preview' : 'done');
        setMessage(diffChanges.length > 0 ? '' : 'No changes generated.');
      } catch (e: any) {
        setStatus('error');
        setMessage(`Error: ${e.message}`);
      }
    };
    loadDiff();
  }, [prompt]);

  // Apply a single change
  const applyChange = async (index: number) => {
    if (applied.has(index)) return;
    const change = changes[index];
    if (!change) return;
    try {
      const fs = new FsTool();
      switch (change.action) {
        case 'add':
        case 'edit':
          await fs.run(['write', change.path, change.content || '']);
          break;
        case 'delete':
          await fs.run(['delete', change.path]);
          break;
      }
      setApplied(prev => new Set(prev).add(index));
    } catch (e: any) {
      setMessage(`Failed to apply ${change.path}: ${e.message}`);
    }
  };

  // Apply all changes
  const applyAll = async () => {
    setStatus('applying');
    for (let i = 0; i < changes.length; i++) {
      await applyChange(i);
    }
    setStatus('done');
    setMessage('All changes applied.');
    onComplete?.();
  };

  // Keyboard navigation
  useInput((input, key) => {
    if (status === 'preview') {
      if (key.upArrow) {
        setSelectedIndex(i => Math.max(0, i - 1));
      } else if (key.downArrow) {
        setSelectedIndex(i => Math.min(changes.length - 1, i + 1));
      } else if (input === 'a') {
        applyChange(selectedIndex);
      } else if (input === 'A') {
        applyAll();
      } else if (input === 'q') {
        setStatus('done');
        onComplete?.();
      }
    }
  });

  if (status === 'loading') {
    return (
      <Box flexDirection="column" borderStyle="round" borderColor={terminalTheme.border} padding={1}>
        <Text color={terminalTheme.accent}>Multi-File Editor</Text>
        <Text color={terminalTheme.muted}>{message}</Text>
      </Box>
    );
  }

  if (status === 'error') {
    return (
      <Box flexDirection="column" borderStyle="round" borderColor={terminalTheme.border} padding={1}>
        <Text color={terminalTheme.accent}>Multi-File Editor</Text>
        <Text color="red">{message}</Text>
      </Box>
    );
  }

  if (status === 'done') {
    return (
      <Box flexDirection="column" borderStyle="round" borderColor={terminalTheme.border} padding={1}>
        <Text color={terminalTheme.accent}>Multi-File Editor</Text>
        <Text color="green">{message}</Text>
        <Text color={terminalTheme.muted}>Applied: {applied.size}/{changes.length} changes</Text>
      </Box>
    );
  }

  return (
    <Box flexDirection="column" borderStyle="round" borderColor={terminalTheme.border} padding={1}>
      <Text color={terminalTheme.accent}>Multi-File Editor</Text>
      <Text color={terminalTheme.muted}>
        ↑↓ navigate | a apply selected | A apply all | q quit
      </Text>
      <Box flexDirection="column" marginTop={1}>
        {changes.map((change, i) => {
          const isSelected = i === selectedIndex;
          const isApplied = applied.has(i);
          const actionColor = change.action === 'add' ? 'green' : change.action === 'delete' ? 'red' : 'yellow';
          return (
            <Box key={i} flexDirection="column">
              <Text color={isSelected ? terminalTheme.accent : terminalTheme.text}>
                {isSelected ? '▶' : ' '} {isApplied ? '✓' : '○'} [{change.action}] {change.path}
              </Text>
              {isSelected && change.content && (
                <Box marginLeft={4} flexDirection="column">
                  {change.content.split('\n').map((line, li) => (
                    <Text key={li} color={terminalTheme.muted}>
                      {line}
                    </Text>
                  ))}
                </Box>
              )}
            </Box>
          );
        })}
      </Box>
      {message && (
        <Box marginTop={1}>
          <Text color="yellow">{message}</Text>
        </Box>
      )}
    </Box>
  );
};

